name: Release Plugins

on:
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - '.vscode'
      - '.idea'

concurrency:
  group: release-ci-group
  cancel-in-progress: true

jobs:
  Plugins:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Build Plugins
        run: pnpm run build

      - name: Packup Buildings
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      # Thanks for GPT-4
      - name: Get the current tag
        run: echo "CURRENT_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Rename file with the current tag
        run: mv dist.zip CsgScratch.${{ env.CURRENT_TAG }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
